import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";

const contracts = resolve(process.argv[2]);
const commit = execFileSync("git", ["rev-parse", "HEAD"], {
  cwd: contracts,
  encoding: "utf8"
}).trim();
const entries = [
  ["AccountCore", "accountCoreAbi"],
  ["SpotRouter", "spotRouterAbi"],
  ["OrderBook", "orderBookAbi"],
  ["SpotPeriphery", "spotPeripheryAbi"],
  ["IERC20Metadata", "erc20MetadataAbi"],
  ["KuruTradingWallet", "kuruTradingWalletAbi"],
  ["WithdrawalLimiter", "withdrawalLimiterAbi"]
];
const metadata = { contractsCommit: commit, artifacts: {} };
const errors = new Map();
let source =
  '// Generated by scripts/sync-abis.mjs from compiled contract artifacts.\nimport type { Abi } from "viem";\n';
for (const [name, binding] of entries) {
  const artifact = `${name}.sol/${name}.json`;
  const { abi } = JSON.parse(readFileSync(resolve(contracts, "out", artifact), "utf8"));
  metadata.artifacts[name] = {
    artifact,
    abiSha256: createHash("sha256").update(JSON.stringify(abi)).digest("hex")
  };
  source += `\nexport const ${binding} = ${JSON.stringify(abi, null, 2)} as const satisfies Abi;\n`;
  for (const item of abi.filter((item) => item.type === "error"))
    errors.set(JSON.stringify(item), item);
}
source += `\nexport const contractAbis = {\n${entries.map(([name, binding]) => `  ${name}: ${binding}`).join(",\n")}\n} as const;\n`;
source += "export type ContractName = keyof typeof contractAbis;\n";
source += `\nexport const kuruErrorAbi = ${JSON.stringify([...errors.values()], null, 2)} as const satisfies Abi;\n`;
writeFileSync("src/generated/abis.ts", source);
writeFileSync(
  "src/generated/metadata.ts",
  `// Generated by scripts/sync-abis.mjs.\nexport const contractMetadata = ${JSON.stringify(metadata, null, 2)} as const;\n`
);
